# List of objects in the world, on the form: 'type': [object names]
objects:
  waypoint:
    - depo
    - drone_start
    - bot_start
    - wp_person0
    - wp_person1
  drone:
    - bebop
  turtlebot:
    - bot0
  person:
    - person0
    - person1
  box: &boxes
    - box0
    - box1
    - box2

# List of where the objects are in the world, on the form: 'waypoint': [object names]
at:
  depo: *boxes
  drone_start:
    - bebop
  bot_start:
    - bot0
  wp_person0:
    - person0
  wp_person1:
    - person1


  # List of waypoint positions, on the form: 'waypoint': [x, y]
waypoints:
  depo:
    x: -2.2
    y: -4.7
  drone_start:
    x: -1.4
    y: -4.8
  bot_start:
    x: -1.7
    y: -4
  wp_person0:
    x: -1.4
    y: -2.2
  wp_person1:
    x: 0.5
    y: -0.1
  
