# List of objects in the world, on the form: 'type': [object names]
objects: 
  waypoint: 
    - depo
    - wp0
    - wp1
    - wp2
    - wp3
  drone:
    - drone0
#    - drone1
  turtlebot:
    - bot0
#    - bot1
  person:
    - person0
    - person1
  box: &boxes
    - box0
    - box1
    - box2

# List of where the objects are in the world, on the form: 'waypoint': [object names]
at:
  depo: *boxes
  wp0:
    - person0
  wp1:
    - person1
  wp2:
    - drone0
  wp3:
    - drone1


  # List of waypoint positions, on the form: 'waypoint': [x, y]
waypoints:
  depo: 
    x: 0
    y: 0
  wp0:
    x: 1
    y: 1
  wp1:
    x: -1
    y: -2
  wp2:
    x: 3
    y: 3
  wp3:
    x: 4
    y: 4
