# List of objects in the world, on the form: 'type': [object names]
objects: 
  waypoint: 
    - depo
    - wp00
    - wp01
    - wp10
    - wp11
    - wp2
    - wp3
  drone:
    - drone
  turtlebot:
    - bot0
#    - bot1
  person:
    - person0
    - person1
  box: &boxes
    - box0
    - box1
    - box2

# List of where the objects are in the world, on the form: 'waypoint': [object names]
at:
  depo: *boxes
  wp00:
    - person0
  wp01:
    - person1
  wp2:
    - drone0
    - bot0
  wp3:
    - drone1


  # List of waypoint positions, on the form: 'waypoint': [x, y]
waypoints:
  depo: 
    x: 0
    y: 0
  wp00:
    x: 1
    y: 1
  wp01:
    x: 2
    y: 1
  wp10:
    x: -1
    y: -1
  wp11:
    x: 0
    y: -1
  wp2:
    x: 3
    y: -2
  wp3:
    x: 2
    y: 2
